---

## https://docs.ansible.com/ansible/latest/network/getting_started/basic_concepts.html
## https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html

- name: A sample playbook
  hosts: all
  remote_user: santiagomr
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    restart_nginx: true

  tasks:

    - name: Run a shell command
      shell: hostname   # https://docs.ansible.com/ansible/latest/modules/shell_module.html
      register: name_of_host


    - name: See the hostname on which I am running
      debug:    # https://docs.ansible.com/ansible/latest/modules/debug_module.html
        var: name_of_host
        verbosity: 0


    - name: Install Nginx (on Debian)
      apt:    # https://docs.ansible.com/ansible/latest/modules/apt_module.html
        name: nginx
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      tags: nginx
      when: ansible_distribution == "Debian"


    - name: Install Nginx (on Fedora)
      yum:  # https://docs.ansible.com/ansible/latest/modules/yum_module.html
        name: nginx
        state: latest
        update_cache: yes
      tags: nginx
      when: ansible_distribution == "Fedora"


    - name: Create a directory if it doesn't exist
      file:   # https://docs.ansible.com/ansible/latest/modules/file_module.html
        path: /var/www/html
        state: directory
        owner: root
        group: root
        mode: "0755"


    - name: Copy ansible logo file to server
      copy:   # https://docs.ansible.com/ansible/latest/modules/copy_module.html
        src: ansible_logo.png
        dest: /var/www/html/logo.png
        owner: root
        group: root
        mode: "0644"


    - name: Set nginx index page
      template:   # https://docs.ansible.com/ansible/latest/modules/template_module.html
        src: index.html.j2
        dest: "/var/www/html/index.html"
        owner: root
        group: root
        mode: "0644"


    - name: Restart nginx service
      service:    # https://docs.ansible.com/ansible/latest/modules/service_module.html
        name: nginx
        state: restarted
      tags: [nginx,services]   # https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html
      when: restart_nginx


- name: A sample of use of roles
  hosts: all
  remote_user: santiagomr
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  roles:
    - role: install_basic_packages  # Install basic packages from a role
      when: inventory_hostname in groups.cluster1   # It would be better to indicate this in the 'hosts' parameter of the task, but this is just an example of use.
